### ISSUE TITLE
Issue installing b3d on a new machine

### ISSUE THREAD

**Issue by georgematheos** [probcomp/b3d#194]
I am trying to set up b3d on a new cloud machine.  After spinning up a Google cloud machine (by using `pixi run gcp-terminal` on my laptop), on the machine, I ran
```
curl -fsSL https://raw.githubusercontent.com/probcomp/b3d/main/install/install.sh | bash
```

The installation got fairly far, but eventually failed with
```bash
→ switching to GPU...

⠠ updating pypi packages in 'gpu'
  ⠴ Preparing distributi [00:00:00] [━━━━╾───────────────]    1/5    building pyliblzfse @ Traceback (most recent call last):
  File "/home/georgematheos/.local/bin/keyring", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/georgematheos/.local/share/pipx/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 219, in main
    return cli.run(argv)
           ^^^^^^^^^^^^^
  File "/home/georgematheos/.local/share/pipx/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 120, in run
    return method()
           ^^^^^^^^
  File "/home/georgematheos/.local/share/pipx/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 132, in do_get
    getattr(self, f'_emit_{self.output_format}')(credential)
  File "/home/georgematheos/.local/share/pipx/venvs/keyring/lib/python3.12/site-packages/keyring/cli.py", line 140, in _emit_plain
    if credential.username:
       ^^^^^^^^^^^^^^^^^^^
  File "/home/georgematheos/.local/share/pipx/venvs/keyring/lib/python3.12/site-packages/keyring/credentials.py", line 39, in username
    raise ValueError("Anonymous credential has no username")
  × gpu: error installing/updating PyPI dependencies
  ├─▶ Failed to prepare distributions
  ├─▶ Failed to fetch wheel: datasync==0.0.2
  ╰─▶ HTTP status client error (401 Unauthorized) for url (https://us-west1-
      python.pkg.dev/probcomp-caliban/probcomp/datasync/datasync-0.0.2-py3-none-
      any.whl#sha256=ce28394757ba65fa1ff3a3010a1f67720f372c877f7d27bc23176a53e2cfa3a4)
```

I tried rerunning after first running
```
gcloud auth application-default login
```
but this did not resolve the issue.

**Comment by georgematheos** [comment]
It seems like a similar issue may have arisen here: https://github.com/probcomp/b3d/pull/193.

**Comment by georgematheos** [comment]
@eightysteele can you please help with this, whenever you have a chance?  If this is a quick thing to fix, it would be valuable to us to fix this as soon as possible!
